<a href="https://colab.research.google.com/github/Bijal1121/Web-Scrapping-using-Python/blob/main/Web_Scraping.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
from bs4 import BeautifulSoup

In [2]:
url = 'https://en.wikipedia.org/wiki/English_Wikipedia'

In [3]:
page = requests.get(url)

In [4]:
page

In [5]:
soup = BeautifulSoup(page.content, 'html.parser')

In [8]:
table = soup.find('table', {'class' : 'ratingstable wikitable plainlinks'})

In [9]:
rows = table.find_all('tr')

In [11]:
table_data = []

In [12]:
for row in rows:
  cells = row.find_all(['th', 'td'])

  row_data = [cell.get_text(strip=True) for cell in cells]

  table_data.append(row_data)

In [13]:
if len(table_data) > 0 and len(table_data[0]) > 0 and table_data[0][0] == 'Rank':
  table_data = table_data[1:]

In [14]:
for row in table_data:
  print(row)

else: print('Failed')

['All rated articles by quality and importance']
['Quality', 'Importance']
['Top', 'High', 'Mid', 'Low', '???', 'Total']
['FA', '1,546', '2,440', '2,361', '1,873', '183', '8,403']
['FL', '168', '632', '717', '672', '108', '2,297']
['A', '352', '680', '782', '574', '84', '2,472']
['GA', '3,121', '7,072', '14,338', '18,704', '1,717', '44,952']
['B', '16,461', '31,889', '52,512', '64,303', '19,486', '184,651']
['C', '16,404', '52,518', '131,019', '290,535', '82,890', '573,366']
['Start', '18,524', '91,328', '409,509', '1,556,960', '393,842', '2,470,163']
['Stub', '4,239', '31,551', '277,929', '2,761,494', '761,799', '3,837,012']
['List', '4,705', '16,625', '52,468', '184,793', '65,885', '324,476']
['Assessed', '65,520', '234,735', '941,635', '4,879,908', '1,325,994', '7,447,792']
['Unassessed', '116', '475', '1,213', '18,536', '412,725', '433,065']
['Total', '65,636', '235,210', '942,848', '4,898,444', '1,738,719', '7,880,857']
Failed

In [15]:
import pandas as pd

In [18]:
df = pd.DataFrame(table_data)

In [19]:
df

,0,1,2,3,4,5,6
0,All rated articles by quality and importance,None,None,None,None,None,None
1,Quality,Importance,None,None,None,None,None
2,Top,High,Mid,Low,???,Total,None
3,FA,"1,546","2,440","2,361","1,873",183,"8,403"
4,FL,168,632,717,672,108,"2,297"
5,A,352,680,782,574,84,"2,472"
6,GA,"3,121","7,072","14,338","18,704","1,717","44,952"
7,B,"16,461","31,889","52,512","64,303","19,486","184,651"
8,C,"16,404","52,518","131,019","290,535","82,890","573,366"
9,Start,"18,524","91,328","409,509","1,556,960","393,842","2,470,163"
10,Stub,"4,239","31,551","277,929","2,761,494","761,799","3,837,012"
11,List,"4,705","16,625","52,468","184,793","65,885","324,476"
12,Assessed,"65,520","234,735","941,635","4,879,908","1,325,994","7,447,792"
13,Unassessed,116,475,"1,213","18,536","412,725","433,065"
14,Total,"65,636","235,210","942,848","4,898,444","1,738,719","7,880,857"

In [21]:
file = 'table_data.xlsx'
df.to_excel(file, index = False)